version: "3"
services:
  ship-certificate-query:
    image: docker.io/nginx:latest
    restart: always # 自动启动
    ports:
      - 8000:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Shanghai
    hostname: ship-certificate-query.docker.vpclub.io
    container_name: ship-certificate-query
    privileged: true